from abc import ABC, abstractmethod
from typing import Any, Dict, List, Optional

class BaseAgentRepository(ABC):
    """
    Abstract Base Class for Agent state persistence.
    Decoupled from FastAPI, enabling future database/Breeth backend swaps.
    """

    @abstractmethod
    def save_agent(self, agent_id: str, persona: Dict[str, Any]) -> None:
        """
        Store a new initialized agent state.
        """
        pass

    @abstractmethod
    def get_agent_persona(self, agent_id: str) -> Optional[Dict[str, Any]]:
        """
        Retrieve persona details for an agent.
        """
        pass

    @abstractmethod
    def get_agent_posts(self, agent_id: str) -> Optional[List[Dict[str, Any]]]:
        """
        Retrieve posts generated by an agent.
        """
        pass

    @abstractmethod
    def agent_exists(self, agent_id: str) -> bool:
        """
        Check if an agent exists in state.
        """
        pass

    @abstractmethod
    def save_prepared_post(self, agent_id: str, post: Dict[str, Any]) -> None:
        """
        Store a prepared/draft post (not yet published).
        """
        pass

    @abstractmethod
    def save_published_post(self, agent_id: str, post: Dict[str, Any]) -> None:
        """
        Store a published post (exposed to feed).
        """
        pass

    @abstractmethod
    def get_prepared_posts(self, agent_id: str) -> Optional[List[Dict[str, Any]]]:
        """
        Retrieve prepared posts generated by an agent.
        """
        pass

    @abstractmethod
    def set_agent_status(self, agent_id: str, status: str) -> None:
        """
        Update the lifecycle status of the agent loop.
        """
        pass

    @abstractmethod
    def get_agent_status(self, agent_id: str) -> Optional[str]:
        """
        Retrieve the current lifecycle status of the agent.
        """
        pass


class InMemoryAgentRepository(BaseAgentRepository):
    """
    In-memory implementation of Agent state persistence.
    """

    def __init__(self) -> None:
        self._agents: Dict[str, Dict[str, Any]] = {}

    def save_agent(self, agent_id: str, persona: Dict[str, Any]) -> None:
        self._agents[agent_id] = {
            "persona": persona,
            "posts": [],  # Initializes with empty published posts list
            "prepared_posts": [],  # Initializes with empty prepared posts list
            "status": "INITIALIZED"  # Default initial state
        }

    def get_agent_persona(self, agent_id: str) -> Optional[Dict[str, Any]]:
        if agent_id in self._agents:
            return self._agents[agent_id]["persona"]
        return None

    def get_agent_posts(self, agent_id: str) -> Optional[List[Dict[str, Any]]]:
        if agent_id in self._agents:
            return self._agents[agent_id]["posts"]
        return None

    def agent_exists(self, agent_id: str) -> bool:
        return agent_id in self._agents

    def save_prepared_post(self, agent_id: str, post: Dict[str, Any]) -> None:
        if agent_id in self._agents:
            self._agents[agent_id]["prepared_posts"].append(post)

    def save_published_post(self, agent_id: str, post: Dict[str, Any]) -> None:
        if agent_id in self._agents:
            self._agents[agent_id]["posts"].append(post)

    def get_prepared_posts(self, agent_id: str) -> Optional[List[Dict[str, Any]]]:
        if agent_id in self._agents:
            return self._agents[agent_id]["prepared_posts"]
        return None

    def set_agent_status(self, agent_id: str, status: str) -> None:
        if agent_id in self._agents:
            self._agents[agent_id]["status"] = status

    def get_agent_status(self, agent_id: str) -> Optional[str]:
        if agent_id in self._agents:
            return self._agents[agent_id]["status"]
        return None


# Global singleton instance for in-memory persistence during the server lifecycle
agent_repository = InMemoryAgentRepository()
