from abc import ABC, abstractmethod
from typing import Any, Dict, List, Optional

class BaseAgentRepository(ABC):
    """
    Abstract Base Class for Agent state persistence.
    Decoupled from FastAPI, enabling future database/Breeth backend swaps.
    """

    @abstractmethod
    def save_agent(self, agent_id: str, persona: Dict[str, Any]) -> None:
        """
        Store a new initialized agent state.
        """
        pass

    @abstractmethod
    def get_agent_persona(self, agent_id: str) -> Optional[Dict[str, Any]]:
        """
        Retrieve persona details for an agent.
        """
        pass

    @abstractmethod
    def get_agent_posts(self, agent_id: str) -> Optional[List[Dict[str, Any]]]:
        """
        Retrieve posts generated by an agent.
        """
        pass

    @abstractmethod
    def agent_exists(self, agent_id: str) -> bool:
        """
        Check if an agent exists in state.
        """
        pass


class InMemoryAgentRepository(BaseAgentRepository):
    """
    In-memory implementation of Agent state persistence.
    """

    def __init__(self) -> None:
        self._agents: Dict[str, Dict[str, Any]] = {}

    def save_agent(self, agent_id: str, persona: Dict[str, Any]) -> None:
        self._agents[agent_id] = {
            "persona": persona,
            "posts": []  # Initializes with empty posts list
        }

    def get_agent_persona(self, agent_id: str) -> Optional[Dict[str, Any]]:
        if agent_id in self._agents:
            return self._agents[agent_id]["persona"]
        return None

    def get_agent_posts(self, agent_id: str) -> Optional[List[Dict[str, Any]]]:
        if agent_id in self._agents:
            return self._agents[agent_id]["posts"]
        return None

    def agent_exists(self, agent_id: str) -> bool:
        return agent_id in self._agents


# Global singleton instance for in-memory persistence during the server lifecycle
agent_repository = InMemoryAgentRepository()
